### ISSUE TITLE
Question on `update_interval` argument

### ISSUE THREAD

**Issue by tpprymjmdr** [ku2482/fqf-iqn-qrdqn.pytorch#10]
Hello @ku2482,

First off, great work on the repo, the code is very well written.

I do have a question regarding the default value of the `update_interval` argument defined [here](https://github.com/ku2482/fqf-iqn-qrdqn.pytorch/blob/72e48a085dcb213e58960ce00fc7347d54aaba5a/fqf_iqn_qrdqn/agent/base_agent.py#L16). As the environment setup mentioned [here](https://github.com/ku2482/fqf-iqn-qrdqn.pytorch/blob/72e48a085dcb213e58960ce00fc7347d54aaba5a/fqf_iqn_qrdqn/env.py#L277) implies we are already skipping to every 4<sup>th</sup> frame, doesn't `update_interval=4` mean the learning occurs every 16th frame?

**Comment by ku2482** [comment]
Hi @tpprymjmdr.

You're right.
I used the same training protocol as the original paper. Please see the paper for more details.

Thanks.

**Comment by tpprymjmdr** [comment]
Thanks for clearing that up @ku2482, appreciate it.
