### ISSUE TITLE
Element-wise product

### ISSUE THREAD

**Issue by slerman12** [ku2482/fqf-iqn-qrdqn.pytorch#17]
I think you're forgetting the element-wise product in the IQN paper, am I wrong? At the end of the first paragraph of section 3.1

**Comment by toshikwa** [comment]
Please refer here.
https://github.com/ku2482/fqf-iqn-qrdqn.pytorch/blob/11d70bb428e449fe5384654c05e4ab2c3bbdd4cd/fqf_iqn_qrdqn/network.py#L173
