### ISSUE TITLE
Could you please help me with the proof for proposition 1?

### ISSUE THREAD

**Issue by xlnwel** [ku2482/fqf-iqn-qrdqn.pytorch#6]
Hi @ku2482 

Thanks for the code. May I ask you a question? 

The author gives proposition 1 and its proof as follows:

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/10184153/86008766-d1006900-ba4b-11ea-943e-a8a7d7409bf5.png">

I'm quite confused about how they compute the third step, which involves the integral over a quantile function. Could you please help me with that?

**Comment by ku2482** [comment]
Hi @xlnwel 

I wrote the rough derivation of the first half(①).
Note that
- we can remove absolute value symbols as we assume non-decreasing property.
- derivative of f(x/2) equals to 1/2 f'(x/2).

If you have any questions, feel free to ask me.

![S__424820743](https://user-images.githubusercontent.com/37267851/86033968-c4443b00-ba74-11ea-9f6c-3cba5758f7e8.jpg)

**Comment by ku2482** [comment]
Hi @xlnwel 

I wrote the rough derivation of the first half(①).
Note that
- we can remove absolute value symbols as we assume non-decreasing property.
- derivative of f(x/2) equals to 1/2 f'(x/2).

If you have any questions, feel free to ask me.

![S__424820744](https://user-images.githubusercontent.com/37267851/86035925-0ae76480-ba78-11ea-89e6-6ac7a0905e48.jpg)

**Comment by xlnwel** [comment]
Hi @ku2482,

Thank you for the derivation, which helps me understand most of the proof. However, I still got several questions. The following derivative is what I wrote

<img width="782" alt="image" src="https://user-images.githubusercontent.com/10184153/86070198-9f6cb980-baae-11ea-92ca-ed1931b571a3.png">

The second and third parts are consistent with yours, but the first and fourth are different. I computed the first and fourth parts from

<img width="212" alt="image" src="https://user-images.githubusercontent.com/10184153/86070560-9defc100-baaf-11ea-86ef-96566a11bf76.png">

but you directly moved the partial derivative inside. May I ask you why?

This affects how to compute

<img width="254" alt="image" src="https://user-images.githubusercontent.com/10184153/86070716-ec9d5b00-baaf-11ea-962e-fa01b8e70aa5.png">

which I compute as follows

<img width="395" alt="image" src="https://user-images.githubusercontent.com/10184153/86072119-6f73e500-bab3-11ea-97c5-f20865b6dc0e.png">

This is quite different from the results of proposition 1. Where did I make mistakes?

**Comment by ku2482** [comment]
Hi.

Oh, you're right. Partial derivative should be placed as the second image you sent.

However, results would be the same.
First and fourth parts are constant, which don't depend on omega.
Because tau_hat is the midpoint and the signs of first and forth parts are opposite, these term should disappear before we apply the partial derivative.

**Comment by xlnwel** [comment]
Hi, @ku2482 

I know that. But could you please help me with the following calculation? I somehow compute the following part wrongly, and I cannot find the error

<img width="304" alt="image" src="https://user-images.githubusercontent.com/10184153/86116291-c0a9c600-baff-11ea-9da9-63c380c10bde.png">

Thanks in advance.

**Comment by ku2482** [comment]
Hi, @xlnwel 

Let me assure you that my derivation only calculates only first part half of the whole derivative as below, is it clear?

<img src="https://user-images.githubusercontent.com/37267851/86117636-5b0f0700-bb0a-11ea-841d-9e52fa2a9026.png" title="graph" width=500>

**Comment by ku2482** [comment]
I wrote down the derivation of **latter half** of the whole derivative.
Please tell me where exactly is bothering you.

![S__425148434](https://user-images.githubusercontent.com/37267851/86118905-80047980-bb0c-11ea-88a7-26bacd16ccf8.jpg)

**Comment by xlnwel** [comment]
Hi, 

I'm not confused by the part you already addressed. I'm confused about the part you omitted. See the following snapshot. I get to a different results from the proof in the paper, but I could not tell where I made a mistake.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/10184153/86131781-aa5c3400-bb18-11ea-95c8-009e6cf67f6c.png">

**Comment by xlnwel** [comment]
Hi, 

Everything is crystal clear now. Thank you so much for the proof:-)
