### ISSUE TITLE
Could you please tell me how it to run 'BreakoutDeterministic-v4'?

### ISSUE THREAD

**Issue by THSWind** [ku2482/fqf-iqn-qrdqn.pytorch#7]
Hello,
Could you please tell me how it to run 'BreakoutDeterministic-v4'?

BTW, I run it by: `python train_iqn.py --cuda --env_id BreakoutNoFrameskip-v4 --seed 0 --config config/iqn.yaml`
and
 `python train_iqn.py --cuda --env_id BreakoutDeterministic-v4 --seed 0 --config config/iqn.yaml` 
I want to compare with, but after run this code, it's return seems strange and not the same as mine. I commented (fqf_iqn_qrdqn/env.py line 275)
`assert 'NoFrameskip' in env.spec.id`
 it seems work, but it's return is strange too. At the beginning of trainning of my code's traning process, it score is larger than your's. It puzzled me

**Comment by ku2482** [comment]
Hi @THSWind 

I don't know why you want to compare `BreakoutNoFrameskip-v4` with `BreakoutDeterministic-v4`.
I suspect that you misunderstand the difference between `Deterministic` and `NoFrameskip`.

Here is the difference.
- `(None)`: frameskip is sampled from [2, 4].
- `Deterministic`: frameskip is fixed to 4.
- `NoFrameskip`: frameskip is fixed to 1. (No frameskip)

I followed the DeepMind's implementation to use `NoFrameskip` and explicitly set frameskip to 4 using a wrapper [here](https://github.com/ku2482/fqf-iqn-qrdqn.pytorch/blob/master/fqf_iqn_qrdqn/env.py#L134).
If you still want to use `Deterministic` env,  please comment out [the assertion](https://github.com/ku2482/fqf-iqn-qrdqn.pytorch/blob/master/fqf_iqn_qrdqn/env.py#L275) and [MaxAndSkipEnv](https://github.com/ku2482/fqf-iqn-qrdqn.pytorch/blob/master/fqf_iqn_qrdqn/env.py#L277).

If you have any other questions, feel free to ask me :)
Thanks!!

**Comment by THSWind** [comment]
@Thanks for your reply~
sry for my expression is not clear. Actually, I didn't misunderstand the difference between `Deterministic` and `NoFrameskip`.

I just want to compare your code's iqn and my another adapted algorithm. I have run `Deterministic-v4`, so I want to run `Deterministic-v4` too.

besides this, I have read your code, it's really a great job! I want to do some change based on it. 
Could you please tell me how to operate the real reward?(Because my research work need it). BTW,  your code looks too organized. One env wrap the other one, it's really hard to read for me.

If you are willing to, we can talk about it through join this discord channal: [](https://discord.gg/UMfWwg)
)

**Comment by ku2482** [comment]
@THSWind 

> Could you please tell me how to operate the real reward?

Please just set `clip_rewards=False` [here](https://github.com/ku2482/fqf-iqn-qrdqn.pytorch/blob/master/train_iqn.py#L15).
Thank you for inviting me :)

**Comment by THSWind** [comment]
hey, @ku2482 
Could you tell me how long have you trained an iqn agent for 100M frames? 1GPU? which machine?
I use an TeslaP40 GPU, but it's speed is very slow
